# Generated by Django 4.2.26 on 2025-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coder',
            field=models.CharField(default='Blaise Smyka', max_length=100),
        ),
    ]
