# Generated by Django 4.2.26 on 2025-11-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_coder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coder',
        ),
    ]
